steps:
  # Step 1: Clone GitHub repo and zip it
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y git zip && \
        git clone https://github.com/20481A04K2/jenkinscloudbuildtocloudrun.git && \
        zip -r jenkinscloudbuildtocloudrun.zip jenkinscloudbuildtocloudrun

  # Step 2: Ensure Artifact Registry exists
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud artifacts repositories describe my-repo --location=asia-east1 --project=euphoric-world-464505-q1; then
          echo "Creating Artifact Registry..."
          gcloud artifacts repositories create my-repo \
            --repository-format=docker \
            --location=asia-east1 \
            --project=euphoric-world-464505-q1
        else
          echo "Artifact Registry already exists."
        fi

  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'jenkinscloudbuildtocloudrun'
    args:
      [
        'build',
        '-t',
        'asia-east1-docker.pkg.dev/euphoric-world-464505-q1/my-repo/my-app-image:latest',
        '.'
      ]

  # Step 4: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-east1-docker.pkg.dev/euphoric-world-464505-q1/my-repo/my-app-image:latest'
      ]

  # Step 5: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        SERVICE_NAME="my-cloudrun-service"
        REGION="asia-east1"
        IMAGE_URI="asia-east1-docker.pkg.dev/euphoric-world-464505-q1/my-repo/my-app-image:latest"

        if gcloud run services describe "$$SERVICE_NAME" --region="$$REGION" --project=euphoric-world-464505-q1 > /dev/null 2>&1; then
          echo "Updating existing Cloud Run service..."
        else
          echo "Creating new Cloud Run service..."
        fi

        gcloud run deploy "$$SERVICE_NAME" \
          --image="$$IMAGE_URI" \
          --platform=managed \
          --region="$$REGION" \
          --allow-unauthenticated \
          --project=euphoric-world-464505-q1

options:
  logging: CLOUD_LOGGING_ONLY
