steps:
  # Step 0: Generate dynamic version tag
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Generate Version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        VERSION_TAG="v-$$(date +%Y%m%d-%H%M%S)"
        echo "VERSION_TAG=$$VERSION_TAG" > /workspace/version.env
        echo "Generated version: $$VERSION_TAG"

  # Step 1: Create Instance Template (Regional) with startup script
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create Instance Template'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        gcloud compute instance-templates create vamsi-template-$$VERSION_TAG \
          --machine-type=e2-medium \
          --region=asia-east1 \
          --image-family=debian-12 \
          --image-project=debian-cloud \
          --tags=http-server,https-server,allow-8080 \
          --metadata=startup-script='#!/bin/bash
          echo "Startup script started."
          apt-get update -y
          apt-get install -y unzip curl python3-pip python3.11-venv
          mkdir -p /home/sajja_vamsi/my-app
          chown -R sajja_vamsi:sajja_vamsi /home/sajja_vamsi/my-app
          cd /home/sajja_vamsi/my-app
          echo "Downloading ZIP..."
          curl -L https://github.com/20481A04K2/jenkinscloudbuildtomig.git -o source.zip
          echo "Unzipping..."
          unzip source.zip -d .
          cd githubtomig-main || exit
          python3 -m venv venv
          source venv/bin/activate
          pip install flask
          nohup python3 app.py --host=0.0.0.0 --port=8080 > /home/sajja_vamsi/app.log 2>&1 &'

  # Step 2: Create or update MIG (Zonal)
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Create or Update MIG'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/version.env
        if ! gcloud compute instance-groups managed describe vamsi-mig --zone=asia-east1-b > /dev/null 2>&1; then
          echo "Creating MIG..."
          gcloud compute instance-groups managed create vamsi-mig \
            --base-instance-name=vamsi-instance \
            --template=vamsi-template-$$VERSION_TAG \
            --size=1 \
            --zone=asia-east1-b
        else
          echo "Updating MIG with new template..."
          gcloud compute instance-groups managed set-instance-template vamsi-mig \
            --template=vamsi-template-$$VERSION_TAG \
            --zone=asia-east1-b
          echo "Rolling restart..."
          gcloud compute instance-groups managed rolling-action restart vamsi-mig \
            --zone=asia-east1-b
        fi

options:
  logging: CLOUD_LOGGING_ONLY
